# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 230)
        Dialog.setMinimumSize(QtCore.QSize(450, 230))
        Dialog.setMaximumSize(QtCore.QSize(450, 230))
        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DialogFrame = QtWidgets.QFrame(Dialog)
        self.DialogFrame.setStyleSheet("QFrame#DialogFrame{\n"
"    border:solid;\n"
"    border-radius:30px;\n"
"    background-color: rgba(50, 6, 150,200);\n"
"}")
        self.DialogFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DialogFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DialogFrame.setObjectName("DialogFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.DialogFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.PBs_layout = QtWidgets.QFrame(self.DialogFrame)
        self.PBs_layout.setMaximumSize(QtCore.QSize(16777215, 50))
        self.PBs_layout.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PBs_layout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PBs_layout.setObjectName("PBs_layout")
        self.BTNS_Layout = QtWidgets.QHBoxLayout(self.PBs_layout)
        self.BTNS_Layout.setContentsMargins(6, -1, -1, -1)
        self.BTNS_Layout.setObjectName("BTNS_Layout")
        self.BTN_Cancel = QtWidgets.QPushButton(self.PBs_layout)
        self.BTN_Cancel.setMinimumSize(QtCore.QSize(0, 40))
        self.BTN_Cancel.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.BTN_Cancel.setStyleSheet("border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"background-color: rgb(255, 70, 73);\n"
"color:black;")
        self.BTN_Cancel.setObjectName("BTN_Cancel")
        self.BTNS_Layout.addWidget(self.BTN_Cancel)
        self.BTN_OK = QtWidgets.QPushButton(self.PBs_layout)
        self.BTN_OK.setMinimumSize(QtCore.QSize(0, 40))
        self.BTN_OK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BTN_OK.setStyleSheet("border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"background-color: rgb(64, 184, 0);\n"
"color:black;")
        self.BTN_OK.setObjectName("BTN_OK")
        self.BTNS_Layout.addWidget(self.BTN_OK)
        self.BTN_OK.raise_()
        self.BTN_Cancel.raise_()
        self.gridLayout.addWidget(self.PBs_layout, 3, 0, 1, 1)
        self.LB_Title = QtWidgets.QLabel(self.DialogFrame)
        self.LB_Title.setObjectName("LB_Title")
        self.gridLayout.addWidget(self.LB_Title, 1, 0, 1, 1)
        self.LB_Message = QtWidgets.QLabel(self.DialogFrame)
        self.LB_Message.setObjectName("LB_Message")
        self.gridLayout.addWidget(self.LB_Message, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.DialogFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BTN_Cancel.setText(_translate("Dialog", "Cancel"))
        self.BTN_OK.setText(_translate("Dialog", "OK"))
        self.LB_Title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffb367;\">Connecting</span><span style=\" font-size:14pt;\"> To ... </span><span style=\" font-size:14pt; color:#04ff00;\">/tty/usb0</span></p></body></html>"))
        self.LB_Message.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#1899ee;\">Serial Number : </span><span style=\" font-size:11pt; color:#37ff00;\">123</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
